# Generated by Django 4.2.6 on 2024-03-11 22:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("fi_status_response", models.CharField(max_length=50)),
                ("link_ref_number", models.CharField(max_length=50)),
                ("fi_status", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "accounts",
            },
        ),
        migrations.CreateModel(
            name="AccountAggregator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aa_name", models.CharField(max_length=255)),
                ("aa_base_path", models.CharField(blank=True, max_length=255)),
                ("aa_webview_url", models.CharField(blank=True, max_length=255)),
                ("aa_vua_suffix", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "account_aggregator",
            },
        ),
        migrations.CreateModel(
            name="ConsentDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consent_payload", models.JSONField()),
                (
                    "consent_handle",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "consent_id",
                    models.UUIDField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("PAUSED", "Paused"),
                            ("REVOKED", "Revoked"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                (
                    "txnid",
                    models.UUIDField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("consent_details", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aa_consents",
                        to="aggregator.accountaggregator",
                    ),
                ),
            ],
            options={
                "db_table": "consent_details",
            },
        ),
        migrations.CreateModel(
            name="ConsentStatusNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("ver", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField()),
                ("txnid", models.UUIDField()),
                ("notifier_type", models.CharField(max_length=10)),
                ("notifier_id", models.CharField(max_length=100)),
                ("consent_id", models.CharField(max_length=100)),
                ("consent_handle", models.CharField(max_length=100)),
                (
                    "consent_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("PENDING", "PENDING"),
                            ("REVOKED", "REVOKED"),
                            ("PAUSED", "PAUSED"),
                            ("REJECTED", "REJECTED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "consent_status_notifications",
            },
        ),
        migrations.CreateModel(
            name="FIStatusNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("ver", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField()),
                ("txnid", models.UUIDField(editable=False, unique=True)),
                ("notifier_type", models.CharField(max_length=50)),
                ("notifier_id", models.CharField(max_length=50)),
                ("session_id", models.CharField(max_length=50)),
                ("session_status", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "fi_status_notifications",
            },
        ),
        migrations.CreateModel(
            name="FIStatusResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("fi_notification", models.CharField(max_length=50)),
                ("fipID", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "fi_status_responses",
            },
        ),
        migrations.CreateModel(
            name="FIUEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiu_name", models.CharField(max_length=255)),
                ("fiu_client_id", models.CharField(max_length=255, unique=True)),
                ("fiu_token_url", models.CharField(max_length=255)),
                ("fiu_client_secret", models.CharField(max_length=255)),
                ("rsa_key_json", models.JSONField()),
                ("pyro_token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fiu_entities",
            },
        ),
        migrations.CreateModel(
            name="SessionDetails",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.CharField(default=None, max_length=100)),
                ("session_status", models.CharField(default=None, max_length=20)),
                ("consent_id", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "session_details",
            },
        ),
        migrations.CreateModel(
            name="FIUCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("pan", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fiu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="aggregator.fiuentity",
                    ),
                ),
            ],
            options={
                "db_table": "fiu_customers",
            },
        ),
        migrations.CreateModel(
            name="FIPData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ver", models.CharField(max_length=10, null=True)),
                ("timestamp", models.DateTimeField()),
                ("txnid", models.CharField(max_length=255, null=True)),
                ("requester_name", models.CharField(max_length=255)),
                ("requester_id", models.CharField(max_length=255)),
                (
                    "entity_info_id",
                    models.CharField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fip_data",
                "indexes": [
                    models.Index(
                        fields=["entity_info_id"], name="fip_data_entity_info_id_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FIDataRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_id", models.CharField(default=None, max_length=100)),
                ("status", models.CharField(default="INITIATED", max_length=20)),
                ("txnid", models.CharField(default="", max_length=128)),
                ("session_id", models.CharField(default="", max_length=128)),
                ("private_key", models.CharField(default="", max_length=1024)),
                ("key_material", models.JSONField(blank=True, null=True)),
                ("fetched_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fi_data_requests",
                        to="aggregator.consentdetail",
                    ),
                ),
            ],
            options={
                "db_table": "fi_data_requests",
            },
        ),
        migrations.AddField(
            model_name="consentdetail",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_consents",
                to="aggregator.fiucustomer",
            ),
        ),
        migrations.AddField(
            model_name="consentdetail",
            name="fiu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiu_consents",
                to="aggregator.fiuentity",
            ),
        ),
        migrations.CreateModel(
            name="FIUAARegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fiu_aa_aes_token",
                    models.CharField(
                        blank=True,
                        help_text="Token used by FIU/AA to encrypt/decrypt redirectURL",
                        max_length=255,
                    ),
                ),
                (
                    "account_aggregator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiu_registrations",
                        to="aggregator.accountaggregator",
                    ),
                ),
                (
                    "fiu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aa_registrations",
                        to="aggregator.fiuentity",
                    ),
                ),
            ],
            options={
                "db_table": "fiu_aa_registration",
                "unique_together": {("fiu", "account_aggregator")},
            },
        ),
        migrations.AddIndex(
            model_name="consentdetail",
            index=models.Index(fields=["consent_handle"], name="consent_handle_idx"),
        ),
    ]
