# Generated by Django 4.2.6 on 2024-03-12 12:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_handle",
                    models.UUIDField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                (
                    "consent_id",
                    models.UUIDField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_logs",
                        to="aggregator.accountaggregator",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_logs",
                        to="aggregator.fiucustomer",
                    ),
                ),
                (
                    "fiu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_logs",
                        to="aggregator.fiuentity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Consent Logs",
                "db_table": "consent_logs",
            },
        ),
    ]
