# Generated by Django 4.2.6 on 2024-03-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0002_consentlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentdetail",
            name="consent_details",
            field=models.JSONField(null=True),
        ),
    ]
