# Generated by Django 4.2.6 on 2024-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0003_alter_consentdetail_consent_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiuentity",
            name="consent_redirection_url",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
